{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "chemchat.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chemchat.labels" . | nindent 4 }}
rules:
{{- with .Values.rbac.rules }}
{{- toYaml . | nindent 0 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "chemchat.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chemchat.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "chemchat.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "chemchat.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
