apiVersion: v1
kind: ConfigMap
metadata:
  name: chemchat-config
  namespace: chemchat
  labels:
    app.kubernetes.io/name: chemchat
    app.kubernetes.io/component: config
data:
  NODE_ENV: "production"
  PORT: "3000"
  DATABASE_URL: "postgresql://chemchat:$(POSTGRES_PASSWORD)@postgres-service:5432/chemchat?schema=public"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  ELASTICSEARCH_NODE: "http://elasticsearch-service:9200"
  KAFKA_BROKERS: "kafka-service:9092"
  KAFKA_CLIENT_ID: "chemchat-api"
  KAFKA_GROUP_ID: "chemchat-consumers"
  JWT_SECRET: "$(JWT_SECRET)"
  JWT_EXPIRES_IN: "15m"
  JWT_REFRESH_EXPIRES_IN: "7d"
  WEBSOCKET_TOKEN_EXPIRES_IN: "1h"
  RATE_LIMIT_WINDOW_MS: "60000"
  RATE_LIMIT_MAX_REQUESTS: "100"
  CORS_ORIGIN: "*"
  SWAGGER_ENABLED: "true"
  LOG_LEVEL: "info"
  METRICS_ENABLED: "true"
  TRACING_ENABLED: "true"
  JAEGER_ENDPOINT: "http://jaeger-collector:14268/api/traces"
  PROMETHEUS_METRICS_PATH: "/metrics"
  HEALTH_CHECK_TIMEOUT: "5000"
  GRACEFUL_SHUTDOWN_TIMEOUT: "30000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chemchat-config-staging
  namespace: chemchat-staging
  labels:
    app.kubernetes.io/name: chemchat
    app.kubernetes.io/component: config
    app.kubernetes.io/instance: staging
data:
  NODE_ENV: "staging"
  PORT: "3000"
  DATABASE_URL: "postgresql://chemchat:$(POSTGRES_PASSWORD)@postgres-service:5432/chemchat_staging?schema=public"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "1"
  ELASTICSEARCH_NODE: "http://elasticsearch-service:9200"
  KAFKA_BROKERS: "kafka-service:9092"
  KAFKA_CLIENT_ID: "chemchat-api-staging"
  KAFKA_GROUP_ID: "chemchat-consumers-staging"
  JWT_SECRET: "$(JWT_SECRET)"
  JWT_EXPIRES_IN: "15m"
  JWT_REFRESH_EXPIRES_IN: "7d"
  WEBSOCKET_TOKEN_EXPIRES_IN: "1h"
  RATE_LIMIT_WINDOW_MS: "60000"
  RATE_LIMIT_MAX_REQUESTS: "200"
  CORS_ORIGIN: "*"
  SWAGGER_ENABLED: "true"
  LOG_LEVEL: "debug"
  METRICS_ENABLED: "true"
  TRACING_ENABLED: "true"
  JAEGER_ENDPOINT: "http://jaeger-collector:14268/api/traces"
  PROMETHEUS_METRICS_PATH: "/metrics"
  HEALTH_CHECK_TIMEOUT: "5000"
  GRACEFUL_SHUTDOWN_TIMEOUT: "30000"
